site:
  title: LabVIEW Community Training Initiative
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://labviewcommunitytraining.github.io/www/en
  start_page: ROOT::index.adoc
  robots: allow
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
  - require: ./antora-navigator-extension
    config_file: ./antora-navigator-en.yml
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
content:
  sources:
  - url: https://github.com/LabVIEWCommunityTraining/Website-Home-Section
    branches: main
    start_paths: en
  - url: https://github.com/LabVIEWCommunityTraining/Website-Course-Template
    branches: [v1.0]
    start_paths: www/en
  - url: https://github.com/LabVIEWCommunityTraining/cti-documentation
    branches: [v1.0, v2.0]
    start_paths: www/en
asciidoc:
  attributes:
    page-component-order: 'ROOT, course-labview, course-template'
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    # shortcut
    lv: LabVIEW(TM)
    wip: This section is under construction
    nt: Need translation from
ui:
  bundle:
    url: https://labviewcommunitytraining.github.io/Website-UI/en/ui-bundle.zip
  supplemental_files:
  - path: partials/footer-scripts.hbs
    contents: ./supplemental-ui/partials/footer-scripts.hbs
  - path: partials/head-meta.hbs
    contents: ./supplemental-ui/partials/head-meta.hbs
  - path: partials/nav.hbs
    contents: ./supplemental-ui/partials/nav.hbs
  - path: js/nav.js
    contents: ./supplemental-ui/js/nav.js
  - path: css/nav.css
    contents: ./supplemental-ui/css/nav.css
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
      - favicon.ico
  - path: .nojekyll